apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  selector:
    matchLabels:
      app: demo
  replicas: 1
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
        - name: demo-service
          image: 01720588884/demo-service:1.0.0
          ports:
            - containerPort: 3000
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 100m

---
apiVersion: v1
kind: Service
metadata:
  name: demo-svc
  labels:
    app: demo
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: demo
